### ISSUE TITLE
Avoiding duplicates

### ISSUE THREAD

**Issue by jhordies** [patchstorage/patchstorage-lv2-uploader#22]
Hello, 
I  was missing mda-epianio on rpi64 so I started building all plugins from mod-plugin-builder.
It takes ages and I would like to share 398 of them but no way I'm going to check manually the 311 already available ones if they are present already. 
I don't want to pollute the repository, can you please advice on the procedure? 
Thanks

PS: mda-epiano failed to build :'(

**Comment by pranciskus** [comment]
Hi! If the plugin was uploaded by a different user, it will be skipped during the push procedure. Patchstorage tracks the unique plugin URIs to avoid any possible duplicates. Cheers!
